name: street_fighter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-300.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_ble_peripheral: ^1.2.6
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.4.0
  playing_cards: ^0.4.1+11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
